# Ensemble Configuration
device: "cuda" # cuda or cpu
ensemble_method: "weighted_average" # Options: 'mean', 'weighted_average', 'max_voting'
output_dir: "./outputs/ensemble_results/"
batch_size: 60
frame_skip: 30
margin: 50
min_face_size: 100
compare_baseline_accuracy: true

datasets:
  ASVspoof2019_LA:
    dataset_path:
    example_video_path:
  faceforensic:
    dataset_path: "./backend/dataset/FaceForensics++"
    example_video_path: "./backend/dataset/FaceForensics++/original/002.mp4"
  kaggle:
    dataset_path:
    example_video_path:
  LAV-DF:
    dataset_path:
    example_video_path:
  FakeAVCeleb:
    dataset_path: "./backend/dataset/FakeAVCeleb_v1.2"
    example_video_path: "./backend/dataset/FakeAVCeleb_v1.2/FakeAVCeleb_v1.2/FakeVideo-RealAudio/African/men/id00076/00109_1.mp4"
    example_video_set_path: "./backend/dataset/FakeAVCeleb_v1.2/FakeAVCeleb_v1.2/test/all_real_videos/"
    metadata: "./backend/dataset/FakeAVCeleb_v1.2/FakeAVCeleb_v1.2/meta_data.csv"


# Individual Model Configurations
models:
  # EfficientNet config for the ensemble
  efficientnet_b1:
    active: true
    architecture: "efficientnet_b1"
    weights_path: "./backend/models/DeepFake_EfficientNet/faceforensic_output/outputs/checkpoints/best_model.pth"
    num_classes: 2 # Real or Fake
    image_size: 240
    ensemble_weight: 0.5
    threshold: 0.5

    # preprocessing:
    #   resize: 380
    #   normalization: "imagenet" # Standard ImageNet mean/std

  xceptionnet:
    weights_path: "./backend/models/XceptionNet-Detector/Deepfake-Detection/output/xception_ff23/best.pkl"

  mesonet:
    active: false
    # architecture: "Meso4" # Options are "Meso1", "Meso4", "MesoInception4"
    # weights_path: "Meso4_DF.h5"           # TODO: turn into "weight" instead of path?
    image_size: 256
    threshold: 0.5

  aasist:
